version: '3'

services:
  django:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=capstone.settings
    command: daphne -b 0.0.0.0 -p 8888 capstone.asgi:application
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:6
    ports:
      - "6379:6379"
